username: username
password: password
checkPeriod: "10" # interval between repo checks in seconds
redisHost: "redis-headless"
redisPort: "6379"

replicaCount: 1

image:
  repository: pmuzyka/githubwatcher
  pullPolicy: Always
  tag: "0.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

resources:
   limits:
     cpu: 100m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
#  minReplicas: 1
#  maxReplicas: 10
#  targetCPUUtilizationPercentage: 80